import { Router } from "express";
import { authRouter } from "./auth.routes";
import { memberRouter } from "./member.routes";
import { rewardRouter } from "./reward.routes";
import { pointsRouter } from "./points.routes";
import { transactionRouter } from "./transaction.routes";
import featureFlagRoutes from "./feature-flag.routes";
import systemSettingRoutes from "./system-setting.routes";
import auditLogRoutes from "./audit-log.routes";
import campaignRoutes from "./campaign.routes";
import notificationRoutes from "./notification.routes";
import referralRoutes from "./referral.routes";
import gamificationRoutes from "./gamification.routes";
import analyticsRoutes from "./analytics.routes";
import uploadRoutes from "./upload.routes";
import { storeRouter } from "./store.routes";
import { productCategoryRouter } from "./product-category.routes";
import { productRouter } from "./product.routes";
import { cartRouter } from "./cart.routes";
import { orderRouter } from "./order.routes";
import { reviewRouter } from "./review.routes";
import { wishlistRouter } from "./wishlist.routes";
import { promotionRouter } from "./promotion.routes";
import { staffRouter } from "./staff.routes";
import { receiptController } from "../controllers/receipt.controller";
import { authenticate } from "../middleware/auth.middleware";
import leaderboardRoutes from "./leaderboard.routes";

export const router = Router();

router.get("/health", (_req, res) => {
  res.json({ status: "ok" });
});

router.use("/auth", authRouter);
router.use("/members", authenticate, memberRouter);
router.use("/rewards", authenticate, rewardRouter);
router.use("/points", authenticate, pointsRouter);
router.use("/transactions", authenticate, transactionRouter);
router.use("/feature-flags", authenticate, featureFlagRoutes);
router.use("/settings", authenticate, systemSettingRoutes);
router.use("/audit-logs", authenticate, auditLogRoutes);
router.use("/campaigns", authenticate, campaignRoutes);
router.use("/notifications", authenticate, notificationRoutes);
router.use("/referrals", authenticate, referralRoutes);
router.use("/gamification", authenticate, gamificationRoutes);
router.use("/analytics", authenticate, analyticsRoutes);
router.use("/upload", authenticate, uploadRoutes);
router.use("/stores", authenticate, storeRouter);
router.use("/product-categories", authenticate, productCategoryRouter);
router.use("/products", authenticate, productRouter);
router.use("/cart", authenticate, cartRouter);
router.use("/orders", authenticate, orderRouter);
router.use("/reviews", authenticate, reviewRouter);
router.use("/wishlist", authenticate, wishlistRouter);
router.use("/promotions", authenticate, promotionRouter);
router.use("/staff", authenticate, staffRouter);
router.get("/orders/:id/receipt", authenticate, receiptController.getReceipt);
router.use("/leaderboard", authenticate, leaderboardRoutes);
